site_name: 'EveMonk Documentation'
site_description: ''
site_url: 'https://evemonk.github.io/docs'

repo_name: 'evemonk/docs'
repo_url: 'https://github.com/evemonk/docs'

copyright: 'Copyright &copy; 2016 - 2019 Igor Zubkov'

nav:
  - Home: index.md
  - Installation:
    - Requirements: installation/requirements.md
    - Eve Online SSO: installation/eve_online_sso.md
    - Environment variables: installation/env.md
    - Docker: installation/docker.md
  - Development:
    - Repositories:  development/repositories.md
    - Architecture: development/architecture.md
    - Docker images: development/docker_images.md

theme: 'material'
